# Generated by Django 5.0.1 on 2026-04-06 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas_platform', '0008_ensure_user_tenants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('deployment_mode', models.CharField(default='client', help_text='Mirrors DEPLOYMENT_MODE for DB lookups without relying on env alone', max_length=32)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pixelcast_client_config', to='saas_platform.tenant')),
            ],
            options={
                'verbose_name': 'Pixelcast client config',
            },
        ),
    ]
