# Generated by Django 5.0.1 on 2026-04-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ensure_ticket_telemetry_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='suppress_operator_bridge_outbound',
            field=models.BooleanField(default=False, help_text='When true, do not push this ticket or its customer replies to the operator bridge (avoids loops).'),
        ),
    ]
