# Generated by Django 5.0.1 on 2026-04-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotherClientState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('instance_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_usage_report_ok_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mother client state',
            },
        ),
    ]
